theme: jekyll-theme-minimal

auto: true
server: true
markdown: kramdown

title: kanta mori
email: contact.kantamori@gmail.com
twitter_username: tuz358
github_username: tuz358

# Google services
google_analytics: UA-101506527-2
